### ISSUE TITLE
deploy.sh fails dues to not finding local devstats repo.

### ISSUE THREAD

**Issue by huygaa11** [cncf/devstats-example#3]
Hi, when I run `deploy.sh` for the first time, it fails during annotation creation. It seems like local repos must be synced.

```
...
2018-09-10 22:31:36 beam/gha2db_sync: ./tags ... 78.573481ms
2018-09-10 22:31:36 beam/gha2db_sync: ./annotations
2018-09-10 22:31:36 beam/gha2db_sync: 2018-09-10 22:31:36 beam/annotations: ./git/git_tags.sh /root/devstats_repos/apache/beam
2018-09-10 22:31:36 beam/annotations: Environment Override: map[GIT_TERMINAL_PROMPT:0]
2018-09-10 22:31:36 beam/annotations: STDERR:
./git/git_tags.sh: line 8: cd: /root/devstats_repos/apache/beam: No such file or directory

2018-09-10 22:31:36 beam/annotations: Command, arguments, environment:
[./git/git_tags.sh /root/devstats_repos/apache/beam]
map[GIT_TERMINAL_PROMPT:0]
Command and arguments:
[./git/git_tags.sh /root/devstats_repos/apache/beam]
map[GIT_TERMINAL_PROMPT:0]
2018-09-10 22:31:36 beam/annotations: Error(time=2018-09-10 22:31:36.196542815 +0000 UTC m=+0.012737069):
Error: 'exit status 3'
Stacktrace:
goroutine 1 [running]:
runtime/debug.Stack(0xc42011d3c0, 0xc42008f3e1, 0xd)
	/usr/lib/go-1.10/src/runtime/debug/stack.go:24 +0xa
...
```

When I run `./run.sh` afterwards, it synces up the repos. However, it fails with: 

```
Error: 'pq: relation "tquick_ranges" does not exist'
```

Then I finally ran `deploy.sh`, which successfully deployed the project. 

Therefore, I am currently running commands in this order to deploy a project:
    1. deploy.sh
    2. run.sh
    3. deploy.sh

However, I would like to just run `deploy.sh` once. How can I modify `deploy.sh` so that it does not fail looking for repos in the first run? I feel like I could call something like `sync repos` from `deploy.sh`. Thanks.

**Comment by lukaszgryglicki** [comment]
Error `tquick_ranges` means that no annotations are found for your project. I think this is due to missing releases tags in the main repo. make sure you set `main_repo` in `projects.yaml` and `annotation_regexp` (it can be `''` to get all releases). Not sure why it fails, it worked for me with Homebrew, but maybe I did some steps before deployment - I will try on a fresh new Ubuntu 18.04 again...

**Comment by huygaa11** [comment]
If it makes things easier, you can use a dockerfile I am using to run Beam on your machine easily.
https://github.com/huygaa11/devstats-example/tree/master/docker

**Comment by huygaa11** [comment]
Here is the [projects.yaml](https://github.com/huygaa11/devstats-example/blob/master/projects.yaml) file I am using. I am increasing the date range to pull data and trying again.

**Comment by huygaa11** [comment]
To be clear, the first failure showed up when I run `deploy.sh`. It says:

```
...
2018-09-10 22:31:36 beam/gha2db_sync: ./tags ... 78.573481ms
2018-09-10 22:31:36 beam/gha2db_sync: ./annotations
2018-09-10 22:31:36 beam/gha2db_sync: 2018-09-10 22:31:36 beam/annotations: ./git/git_tags.sh /root/devstats_repos/apache/beam
2018-09-10 22:31:36 beam/annotations: Environment Override: map[GIT_TERMINAL_PROMPT:0]
2018-09-10 22:31:36 beam/annotations: STDERR:
./git/git_tags.sh: line 8: cd: /root/devstats_repos/apache/beam: No such file or directory

2018-09-10 22:31:36 beam/annotations: Command, arguments, environment:
[./git/git_tags.sh /root/devstats_repos/apache/beam]
map[GIT_TERMINAL_PROMPT:0]
Command and arguments:
[./git/git_tags.sh /root/devstats_repos/apache/beam]
map[GIT_TERMINAL_PROMPT:0]
2018-09-10 22:31:36 beam/annotations: Error(time=2018-09-10 22:31:36.196542815 +0000 UTC m=+0.012737069):
Error: 'exit status 3'
Stacktrace:
goroutine 1 [running]:
runtime/debug.Stack(0xc42011d3c0, 0xc42008f3e1, 0xd)
	/usr/lib/go-1.10/src/runtime/debug/stack.go:24 +0xa
...
```

**Comment by lukaszgryglicki** [comment]
I'll take a look tomorrow - I'll clone your fork and see if I can replicate the bug. It looks kind of like get_repos was called in wrong order. Will let you know what I've found.

**Comment by huygaa11** [comment]
Thanks so much for helping out :).

One thing I was not sure during my development was that our org name [apache] is different than our project name [beam], which made me a little confused about when to use org name or project name when I replaced the Homebrew code. Therefore, I may have made mistakes.

**Comment by lukaszgryglicki** [comment]
That may be it. I'll clone your repo tomorrow and recreate step-by-step, eventually updating original docs. Possibly (if I fix this) you will have to merge with upstream (my repo).

**Comment by lukaszgryglicki** [comment]
Speaking about Apache (org) and Beam (project). Do you need to track full org (command line = apache [here](https://github.com/huygaa11/devstats-example/blob/master/projects.yaml#L8)) or you just need Beam only?
If you only need Beam (one repo), you should set the command line to:
```
    command_line:
      - apache
      - beam
```

I think you just need 'beam' repo, because you specified apache beam [here](https://github.com/huygaa11/devstats-example/blob/master/beam/psql.sh#L17).

Your annotations regexp `annotation_regexp: '^\d+\.\d+\.\d+$'` won't find any annotations because Beam's release tags match `annotation_regexp: '^v\d+\.\d+\.\d+$'`. Your annotation regexp would catch `2.3.0` but Beam uses `v2.3.0` instead. You can also specify `annotation_regexp: '^\d+\.\d+\.\d+'` to catch `v2.3.0-RC1` or even `annotation_regexp: ''` to catch all.

Your projects start date `2018-09-03` will only go back to 3rd of September while 1st release tag is on `Jun 1, 2016`: `0.1.0-incubating-1`. I would set projects start date `2016-05-01` to include more historical data.

I would use `Beam` as Org name in `devel/deploy_all.sh` but this is not needed and using just `Apache` is not a bug (this is an org name for Grafana).

**Comment by lukaszgryglicki** [comment]
I've fixed the problem upstream (lukaszgryglicki/devstats), it was a missing `shared/get_repos.sh` [call](https://github.com/cncf/devstats-example/commit/4ab52968bbbd6a2092f4ca90267d4a0d581dd0a0). My suggested improvements for `Beam` in this patch:
[lukaszgryglicki-fix-3.txt](https://github.com/cncf/devstats-example/files/2391325/lukaszgryglicki-fix-3.txt)

Let me know if I can close this.

**Comment by huygaa11** [comment]
This worked great! Thank you.
